server:
  port: 8890

  servlet:
    context-path: /

  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 50
      max: 1000

management:
  #  health:
  #    elasticsearch:
  #      enabled: false
  #    datasource:
  #      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: common-api
  boot:
    admin:
      client:
        url: http://127.0.0.1:8000
  cache:
    type: redis
  # Redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: lilishop
    lettuce:
      pool:
        max-active: 200
        max-wait: 20
        max-idle: 10
        min-idle: 8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false

  shardingsphere:
    datasource:
      names: default-datasource
      default-datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/lilishop?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
        username: root
        password: lilishop
        maxActive: 20
        initialSize: 5
        maxWait: 60000
        minIdle: 5
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        maxOpenPreparedStatements: -1
        filters: stat,wall,log4j2
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true
        loginUsername: druid
        loginPassword: druid
    #    sharding:
    #      default-data-source-name: default-datasource
    #      tables:
    #        li_order:
    #          actual-data-nodes: data2020.li_order_$->{2019..2021}_$->{01..12}
    #          table-strategy:
    #            standard:
    #              sharding-column: create_time
    #              precise-algorithm-class-name: cn.lili.mybatis.sharding.CreateTimeShardingTableAlgorithm
    #              range-algorithm-class-name: cn.lili.mybatis.sharding.CreateTimeShardingTableAlgorithm
    props:
      sql:
        show: false

ignored:
  urls:
    - /editor-app/**
    - /actuator**
    - /actuator/**
    - /MP_verify_qSyvBPhDsPdxvOhC.txt
    - /weixin/**
    - /source/**
    - /common/common/slider/**
    - /common/common/sms/**
    - /common/common/logo
    - /common/common/site
    - /druid/**
    - /swagger-ui.html
    - /doc.html
    - /swagger-resources/**
    - /swagger/**
    - /webjars/**
    - /v2/api-docs
    - /configuration/ui
    - /boot-admin
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico

swagger:
  title: lili API接口文档
  description: lili Api Documentation
  version: 1.0.0
  termsOfServiceUrl: https://pickmall.cn
  contact:
    name: lili
    url: https://pickmall.cn
    email: admin@pickmall.com

# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    cache-enabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
  #    org.hibernate: debug
  #    org.springframework: debug
  file:
    path: lili-logs
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 5MB
jasypt:
  encryptor:
    password: lili

lili:
  verification-code:
    effectiveTime: 300
    watermark: LILI-SHOP
    interfereNum: 0
    faultTolerant: 3
  sms:
    LOGIN: SMS_205755300
    REGISTER: SMS_205755298
    FIND_USER: SMS_205755301
    UPDATE_PASSWORD: SMS_205755297
    WALLET_PASSWORD: SMS_205755301
  system:
    isTestModel: true
  statistics:
    onlineMember: 48
    currentOnlineUpdate: 600
  lbs:
    key: 4BYBZ-7MT6S-PUAOA-6BNWL-FJUD7-UUFXT
    sk: zhNKVrJK6UPOhqIjn8AQvG37b9sz6
  domain:
    pc: https://pc.b2b2c.pickmall.cn
    wap: https://m.b2b2c.pickmall.cn
    store: https://store.b2b2c.pickmall.cn
    admin: https://admin.b2b2c.pickmall.cn
  api:
    buyer: https://buyer-api.pickmall.cn
    common: https://common-api.pickmall.cn
    manager: https://admin-api.pickmall.cn
    store: https://store-api.pickmall.cn

  jwt-setting:
    tokenExpireTime: 60

  cache:
    timeout: 1500
  thread:
    corePoolSize: 5
    maxPoolSize: 50
    queueCapacity: 50
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9200
      index:
        number-of-replicas: 0
        number-of-shards: 3
      index-prefix: lili
      schema: http
    #      account:
    #        username: elastic
    #        password: LiLiShopES
    logstash:
      server: 127.0.0.1:4560
    rocketmq:
      promotion-topic: lili_promotion_topic
      promotion-group: lili_promotion_group
      msg-ext-topic: lili_msg_topic
      msg-ext-group: lili_msg_group
      goods-topic: lili_goods_topic
      goods-group: lili_goods_group
      order-topic: lili_order_topic
      order-group: lili_order_group
      member-topic: lili_member_topic
      member-group: lili_member_group
      other-topic: lili_other_topic
      other-group: lili_other_group
      notice-topic: lili_notice_topic
      notice-group: lili_notice_group
      notice-send-topic: lili_send_notice_topic
      notice-send-group: lili_send_notice_group
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: lili_group
    send-message-timeout: 30000

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:9001/xxl-job-admin
    executor:
      appname: xxl-job-executor-lilishop
      address:
      ip:
      port: 8891
      logpath: ./xxl-job/executor
      logretentiondays: 7